export const characters = [
  {
    name: "Mikasa Ackerman",
    show: "Attack on Titan",
    strength: "Speed",
    weakness: "Emotions",
    class: "Warrior",
    cost: 60,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Light Yagami",
    show: "Death Note",
    strength: "Intelligence",
    weakness: "Hubris",
    class: "Strategist",
    cost: 85,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Edward Elric",
    show: "Fullmetal Alchemist",
    strength: "Intelligence",
    weakness: "Lack of Power",
    class: "Mage",
    cost: 70,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Guts",
    show: "Berserk",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 90,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Kirito",
    show: "Sword Art Online",
    strength: "Speed",
    weakness: "Emotions",
    class: "Swordsman",
    cost: 65,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Saitama",
    show: "One Punch Man",
    strength: "High Combat Power",
    weakness: "Hubris",
    class: "Warrior",
    cost: 100,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Alucard",
    show: "Hellsing",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 95,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Rin Tohsaka",
    show: "Fate/Stay Night",
    strength: "Intelligence",
    weakness: "Emotions",
    class: "Mage",
    cost: 80,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Natsu Dragneel",
    show: "Fairy Tail",
    strength: "High Combat Power",
    weakness: "Lack of Power",
    class: "Warrior",
    cost: 85,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Kenshin Himura",
    show: "Rurouni Kenshin",
    strength: "Speed",
    weakness: "Past",
    class: "Swordsman",
    cost: 75,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Levi Ackerman",
    show: "Attack on Titan",
    strength: "Speed",
    weakness: "Emotions",
    class: "Warrior",
    cost: 80,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Shinobu Kocho",
    show: "Demon Slayer",
    strength: "Accuracy",
    weakness: "Emotions",
    class: "Mage",
    cost: 70,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Zoro Roronoa",
    show: "One Piece",
    strength: "High Combat Power",
    weakness: "Hubris",
    class: "Swordsman",
    cost: 90,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Roronoa Zoro",
    show: "One Piece",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Swordsman",
    cost: 90,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Inosuke Hashibira",
    show: "Demon Slayer",
    strength: "High Combat Power",
    weakness: "Lack of Power",
    class: "Warrior",
    cost: 80,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Yato",
    show: "Noragami",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 85,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Tsubasa Kazanari",
    show: "Symphogear",
    strength: "Speed",
    weakness: "Emotions",
    class: "Archer",
    cost: 65,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Alphonse Elric",
    show: "Fullmetal Alchemist",
    strength: "Intelligence",
    weakness: "Lack of Power",
    class: "Mage",
    cost: 60,
    image_url: "",
    alt_text: "",
  },
  {
    name: "Saber",
    show: "Fate/Stay Night",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 90,
    image_url: "",
    alt_text: "",
  },
];
