export const characters = [
  {
    name: "Mikasa Ackerman",
    show: "Attack on Titan",
    strength: "Speed",
    weakness: "Emotions",
    class: "Warrior",
    cost: 60,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD4dGv7jnp3rdfLVnbE3XDifNuzIMEjOq1yg&s",
    alt_text: "Mikasa Ackerman",
  },
  {
    name: "Light Yagami",
    show: "Death Note",
    strength: "Intelligence",
    weakness: "Hubris",
    class: "Strategist",
    cost: 85,
    image_url:
      "https://i.pinimg.com/236x/24/50/6d/24506d71d06e5c15f325555ce64f1514.jpg",
    alt_text: "Light Yagami",
  },
  {
    name: "Edward Elric",
    show: "Fullmetal Alchemist",
    strength: "Intelligence",
    weakness: "Lack of Power",
    class: "Mage",
    cost: 70,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR42kTxoiHog4G81h6GER3BIiNoMhjCZjGXqA&s",
    alt_text: "Edward Elric",
  },
  {
    name: "Guts",
    show: "Berserk",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 90,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbDZQu-6rYvD0XN6lgopU0FlC4GY79g7507g&s",
    alt_text: "Guts",
  },
  {
    name: "Kirito",
    show: "Sword Art Online",
    strength: "Speed",
    weakness: "Emotions",
    class: "Swordsman",
    cost: 65,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR6MIFGmDvrROJFzHJKHiOJ20r3cjQQxTcMQ&s",
    alt_text: "Kirito",
  },
  {
    name: "Saitama",
    show: "One Punch Man",
    strength: "High Combat Power",
    weakness: "Hubris",
    class: "Warrior",
    cost: 100,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpU3X4v_hR65GlR_UqTKm8neFiEn32iG8Oqg&s",
    alt_text: "Saitama",
  },
  {
    name: "Alucard",
    show: "Hellsing",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 95,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnlL_6jVfmIz8ZsWiAnWPJ7hn_8rCyOfTdnw&s",
    alt_text: "Alucard",
  },
  {
    name: "Rin Tohsaka",
    show: "Fate/Stay Night",
    strength: "Intelligence",
    weakness: "Emotions",
    class: "Mage",
    cost: 80,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyQyYVy4bqKOM7T8QBy7DMFIDy5vCnCKCWeA&",
    alt_text: "Rin",
  },
  {
    name: "Natsu",
    show: "Fairy Tail",
    strength: "High Combat Power",
    weakness: "Lack of Power",
    class: "Warrior",
    cost: 85,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCgdiU_PlgEaZHeROhWEApbTm9IJ9LiUK3Pw&s",
    alt_text: "Natsu",
  },
  {
    name: "Himura",
    show: "Rurouni Kenshin",
    strength: "Speed",
    weakness: "Past",
    class: "Swordsman",
    cost: 75,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHyWoOA0Jo6igGbQ-dTc-Aw8hebBb2QwVP9Q&s",
    alt_text: "Himura",
  },
  {
    name: "Levi Ackerman",
    show: "Attack on Titan",
    strength: "Speed",
    weakness: "Emotions",
    class: "Warrior",
    cost: 80,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg7QsqJx_NfGnuCommfKO7IZcjdwZRwuSSmg&s",
    alt_text: "Levi",
  },
  {
    name: "Shinobu",
    show: "Demon Slayer",
    strength: "Accuracy",
    weakness: "Emotions",
    class: "Mage",
    cost: 70,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-G5BhyfeiXFGRSLLx3nfmx3UXMIcms2pZ6g&s",
    alt_text: "Shinobu",
  },
  {
    name: "Mugen",
    show: "Samurai Champloo",
    strength: "High Combat Power",
    weakness: "Impulsiveness",
    class: "Swordsman",
    cost: 90,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR5GvnijyGAhAflXeSnIDYKm2NVWb5Bqi7Bg&s",
    alt_text: "Mugen",
  },
  {
    name: "Zoro",
    show: "One Piece",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Swordsman",
    cost: 90,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPv0oUFHyHw3t1pluQw2dQRh0aWLJhkhp7AQ&s",
    alt_text: "Zoro",
  },
  {
    name: "Inosuke",
    show: "Demon Slayer",
    strength: "High Combat Power",
    weakness: "Lack of Power",
    class: "Warrior",
    cost: 80,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSleVJ6bte72wdgwt_Y20pCjAzZMCUfMxkpCg&s",
    alt_text: "Inosuke",
  },
  {
    name: "Yato",
    show: "Noragami",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 85,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXpJ0MjPD2wgRO7vgxo1hR2vOXhrCivn1xEw&s",
    alt_text: "Yato",
  },
  {
    name: "Tsubasa",
    show: "Symphogear",
    strength: "Speed",
    weakness: "Emotions",
    class: "Archer",
    cost: 65,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRytssVQqlPFYEaFGdg064PXN5cfO_bV6ji5A&s",
    alt_text: "Tsubasa",
  },
  {
    name: "Alphonse Elric",
    show: "Fullmetal Alchemist",
    strength: "Intelligence",
    weakness: "Lack of Power",
    class: "Mage",
    cost: 60,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyS2LFV0Jp8UFm8Eounf8PmIg5oVIARXbbrw&s",
    alt_text: "Alphonse Elric",
  },
  {
    name: "Saber",
    show: "Fate/Stay Night",
    strength: "High Combat Power",
    weakness: "Past",
    class: "Warrior",
    cost: 90,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEGZ2zFTFH21rcNfxAykaLDKquOgYBowMuGA&s",
    alt_text: "Saber",
  },
];
